// Generated by gen-manifest.ts — do not edit manually

interface ExifData {
	camera: string | null;
	aperture: number | null;
	shutterSpeed: string | null;
	iso: number | null;
	focalLength: number | null;
	dateTaken: string | null;
}

interface ImageVariant {
	width: number;
	format: 'webp' | 'jpeg';
	url: string;
	original?: boolean;
	size?: number;
}

interface ManifestEntry {
	id: string;
	hash: string;
	originalWidth: number;
	originalHeight: number;
	alt: string;
	exif: ExifData;
	variants: ImageVariant[];
}

interface Manifest {
	version: number;
	r2BaseUrl: string;
	images: ManifestEntry[];
}

const manifest: Manifest = {
	version: 2,
	r2BaseUrl: '',
	images: [
		{
			id: 'IMG-20250413-WA0367',
			hash: 'sha256:e07b6faeffa90dd6b8e0183332e48bb2779856a9a032617dd5e3176af0793e9c',
			originalWidth: 1188,
			originalHeight: 1585,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: '2026-08-05'
			},
			variants: [
				{
					width: 1188,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0367.jpg',
					original: true,
					size: 1513633
				}
			]
		},
		{
			id: 'IMG-20250413-WA0440',
			hash: 'sha256:26339db7cc1033c812944a81a08bd547be1857fd8ad5723d1a7e407a1000b9c7',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0440.jpg',
					original: true,
					size: 534943
				}
			]
		},
		{
			id: 'IMG-20250413-WA0435',
			hash: 'sha256:33ad42ae44f068fef17ba25acf109ad03f587309dc505d09429a93b3717eac25',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0435.jpg',
					original: true,
					size: 379722
				}
			]
		},
		{
			id: 'IMG-20250413-WA0413',
			hash: 'sha256:fe8213eab84d48931b2d42846eb912ee5e98e11f6ca3b22fc076af34dc41f02a',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0413.jpg',
					original: true,
					size: 193502
				}
			]
		},
		{
			id: 'IMG-20250413-WA0404',
			hash: 'sha256:dfe4cd0a55e5f1633b0bf14ae724050d147eb781709bab9ebf975fbbb55cad39',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0404.jpg',
					original: true,
					size: 617941
				}
			]
		},
		{
			id: 'IMG-20250413-WA0403',
			hash: 'sha256:37f24a2aea7b0d06ccc3e7a26799f4dfd03c4e1f9614824f9607891c76c0a3cf',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0403.jpg',
					original: true,
					size: 416566
				}
			]
		},
		{
			id: 'IMG-20250413-WA0385',
			hash: 'sha256:4ddef44a235f7b6be201d5fa0f951f00f09ac8e760414a251875d2f7b30e048b',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0385.jpg',
					original: true,
					size: 332366
				}
			]
		},
		{
			id: 'IMG-20250413-WA0225',
			hash: 'sha256:6e50e850974402708c260aa7fb64bbb8ce135c3d45b491f92f781a4b69c304e6',
			originalWidth: 2048,
			originalHeight: 1536,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2048,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0225.jpg',
					original: true,
					size: 344474
				}
			]
		},
		{
			id: 'IMG-20250413-WA0223',
			hash: 'sha256:b1352542427da25f01b8dbe10af5e0d599fc48f0d3c74bf635ea8fa5df08fb08',
			originalWidth: 1536,
			originalHeight: 2048,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1536,
					format: 'jpeg',
					url: '/pics/IMG-20250413-WA0223.jpg',
					original: true,
					size: 387426
				}
			]
		},
		{
			id: '20260801_145840',
			hash: 'sha256:59c058d8d9d89eea085444ea1e598d1dff9c1bdd4474817eb6d2b6169e593e76',
			originalWidth: 1472,
			originalHeight: 3187,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1472,
					format: 'jpeg',
					url: '/pics/20260801_145840.jpg',
					original: true,
					size: 1434995
				}
			]
		},
		{
			id: '20260801_135430',
			hash: 'sha256:32f9d65790f202e030ff243f2b9d871504db481ae72f90919d55c6d0644e5c29',
			originalWidth: 2198,
			originalHeight: 1015,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2198,
					format: 'jpeg',
					url: '/pics/20260801_135430.jpg',
					original: true,
					size: 1358402
				}
			]
		},
		{
			id: '20260801_135338',
			hash: 'sha256:4e1d4656ac40710117401ce6c0223accb9b214ae1be7bdbadf59ef0c90561701',
			originalWidth: 2060,
			originalHeight: 951,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2060,
					format: 'jpeg',
					url: '/pics/20260801_135338.jpg',
					original: true,
					size: 1048499
				}
			]
		},
		{
			id: '20260801_135334',
			hash: 'sha256:bfd971dec4404700597eeaeba83608775cdea5fe491807becc5b72e3b1c56884',
			originalWidth: 2255,
			originalHeight: 1041,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2255,
					format: 'jpeg',
					url: '/pics/20260801_135334.jpg',
					original: true,
					size: 1123816
				}
			]
		},
		{
			id: '20260801_135048',
			hash: 'sha256:88ab47780974f8b98bb04c793b87f21e29b2073e51e634299d3275f8017aabc0',
			originalWidth: 2398,
			originalHeight: 1107,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2398,
					format: 'jpeg',
					url: '/pics/20260801_135048.jpg',
					original: true,
					size: 1135862
				}
			]
		},
		{
			id: '20260801_135047',
			hash: 'sha256:8a76496742d309211e659187d208d1b1089c6c9d9835cd1ef8798c08bdb8524a',
			originalWidth: 2136,
			originalHeight: 986,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2136,
					format: 'jpeg',
					url: '/pics/20260801_135047.jpg',
					original: true,
					size: 1135910
				}
			]
		},
		{
			id: '20260801_133708',
			hash: 'sha256:60c8d068d88cd70c1ace2c595208980369d9f51cca7052d82d26846411a7ae56',
			originalWidth: 3013,
			originalHeight: 1391,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 3013,
					format: 'jpeg',
					url: '/pics/20260801_133708.jpg',
					original: true,
					size: 1187915
				}
			]
		},
		{
			id: '20260723_212124',
			hash: 'sha256:0124fbd8bb1166a5cb8c46d092392eb51b9be08d9e8a501b9d865e365b562df7',
			originalWidth: 5250,
			originalHeight: 2424,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 5250,
					format: 'jpeg',
					url: '/pics/20260723_212124.jpg',
					original: true,
					size: 2378148
				}
			]
		},
		{
			id: '20260723_204806',
			hash: 'sha256:d36be39da3659df1425ffdf92ed5c38dd11ca0213925a7ada4f9e5a7e8e02aa0',
			originalWidth: 2989,
			originalHeight: 1380,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2989,
					format: 'jpeg',
					url: '/pics/20260723_204806.jpg',
					original: true,
					size: 1088568
				}
			]
		},
		{
			id: '20260716_114911',
			hash: 'sha256:ae932777c3ad71c1430ceaadcc78ebbbea44a934f0298d3fa377d0b81a621b0c',
			originalWidth: 1540,
			originalHeight: 1540,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1540,
					format: 'jpeg',
					url: '/pics/20260716_114911.jpg',
					original: true,
					size: 1358616
				}
			]
		},
		{
			id: '20250410_153124',
			hash: 'sha256:0c6d3cecde0d92153c10cf358159af62f51e0f001068d102ae5dee351dcc6951',
			originalWidth: 1044,
			originalHeight: 2261,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1044,
					format: 'jpeg',
					url: '/pics/20250410_153124.jpg',
					original: true,
					size: 1019433
				}
			]
		},
		{
			id: '20250409_195106',
			hash: 'sha256:e49a95db69e38e6f53634e03d4aaa02bd4bacc368f3e5a0539de8dfc40870c97',
			originalWidth: 2521,
			originalHeight: 1164,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2521,
					format: 'jpeg',
					url: '/pics/20250409_195106.jpg',
					original: true,
					size: 1271983
				}
			]
		},
		{
			id: '20250407_164348',
			hash: 'sha256:f680b53b49546e1afe7c2ee32dacee4918943c953c5d9651c94219875cede70c',
			originalWidth: 2543,
			originalHeight: 1174,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2543,
					format: 'jpeg',
					url: '/pics/20250407_164348.jpg',
					original: true,
					size: 743665
				}
			]
		},
		{
			id: '20250406_221421',
			hash: 'sha256:b8d08468f3ce7db4fe3eb4a3499bc89c0bc793e29d50f11e09cd02cb1b521456',
			originalWidth: 3875,
			originalHeight: 1789,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 3875,
					format: 'jpeg',
					url: '/pics/20250406_221421.jpg',
					original: true,
					size: 1757498
				}
			]
		},
		{
			id: '20250403_142623',
			hash: 'sha256:3a1a13d48d205ce10e3f1e3764037e5cfff7cbc3da0b53e9141d934fb54a157c',
			originalWidth: 2520,
			originalHeight: 1164,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2520,
					format: 'jpeg',
					url: '/pics/20250403_142623.jpg',
					original: true,
					size: 1029923
				}
			]
		},
		{
			id: '20250403_135438',
			hash: 'sha256:9b9784f58dcd3edbfff510bc5fd5704ddaefb7ed8429b901d53cf1a51e84b639',
			originalWidth: 1630,
			originalHeight: 3530,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 1630,
					format: 'jpeg',
					url: '/pics/20250403_135438.jpg',
					original: true,
					size: 1229378
				}
			]
		},
		{
			id: '20250331_165854',
			hash: 'sha256:47404f5da59aecd3a6154d9aa8831dc183e8bc36c32f6292f95c2d69d2da02c8',
			originalWidth: 2166,
			originalHeight: 1000,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2166,
					format: 'jpeg',
					url: '/pics/20250331_165854.jpg',
					original: true,
					size: 1042659
				}
			]
		},
		{
			id: '20250331_134758',
			hash: 'sha256:40a16e51085fdf0d4056fcc090950ad7aea2a04cf1efaa6ab238b3e97f400eab',
			originalWidth: 759,
			originalHeight: 1643,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 759,
					format: 'jpeg',
					url: '/pics/20250331_134758.jpg',
					original: true,
					size: 831240
				}
			]
		}
	]
};

export default manifest;
