#!/usr/bin/env bun
/**
 * Lightweight manifest generator — reads image metadata only (no resizing).
 * Copies JPGs to static/pics/ and writes a manifest pointing to local paths.
 *
 * Usage: bun run scripts/gen-manifest.ts
 */

import { readdir, copyFile, writeFile } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';
import * as exifr from 'exifr';
import prettier from 'prettier';

const IMAGES_DIR = join(import.meta.dir, '..', 'src', 'content', 'images');
const STATIC_PICS = join(import.meta.dir, '..', 'static', 'pics');
const MANIFEST_PATH = join(import.meta.dir, '..', 'src', 'content', 'images', 'manifest.ts');

// ── EXIF helpers (same as sync-pics.ts but lighter) ─────────────────

function formatShutterSpeed(exposure: number | undefined): string | null {
	if (exposure === undefined || exposure === null) return null;
	if (exposure >= 1) return `${exposure}`;
	const denominator = Math.round(1 / exposure);
	return `1/${denominator}`;
}

function formatCamera(make: string | undefined, model: string | undefined): string | null {
	if (!make && !model) return null;
	if (!make) return model!.trim();
	if (!model) return make.trim();
	const trimmedMake = make.trim();
	const trimmedModel = model.trim();
	if (trimmedModel.toLowerCase().startsWith(trimmedMake.toLowerCase())) return trimmedModel;
	return `${trimmedMake} ${trimmedModel}`;
}

async function extractExif(buffer: Buffer) {
	try {
		const parsed = await exifr.parse(buffer, {
			pick: ['Make', 'Model', 'FNumber', 'ExposureTime', 'ISO', 'FocalLength', 'DateTimeOriginal'],
			gps: false
		});
		if (!parsed) return emptyExif();
		return {
			camera: formatCamera(parsed.Make, parsed.Model),
			aperture: parsed.FNumber ?? null,
			shutterSpeed: formatShutterSpeed(parsed.ExposureTime),
			iso: parsed.ISO ?? null,
			focalLength: parsed.FocalLength ?? null,
			dateTaken: parsed.DateTimeOriginal
				? new Date(parsed.DateTimeOriginal).toISOString().slice(0, 10)
				: null
		};
	} catch {
		return emptyExif();
	}
}

function emptyExif() {
	return {
		camera: null,
		aperture: null,
		shutterSpeed: null,
		iso: null,
		focalLength: null,
		dateTaken: null
	};
}

// ── Main ────────────────────────────────────────────────────────────

async function main() {
	// Ensure static/pics exists
	await Bun.write(join(STATIC_PICS, '.gitkeep'), '');

	const files = (await readdir(IMAGES_DIR)).filter((f) => {
		const ext = extname(f).toLowerCase();
		return ['.jpg', '.jpeg'].includes(ext) && !f.startsWith('.');
	});

	console.log(`Found ${files.length} images`);

	const images = [];

	for (const filename of files) {
		const srcPath = join(IMAGES_DIR, filename);
		const dstPath = join(STATIC_PICS, filename);
		const id = basename(filename, extname(filename));

		// Copy to static/pics
		await copyFile(srcPath, dstPath);
		console.log(`  Copied: ${filename}`);

		// Read metadata only
		const buffer = await Bun.file(srcPath).arrayBuffer();
		const hash = 'sha256:' + createHash('sha256').update(new Uint8Array(buffer)).digest('hex');
		const metadata = await sharp(srcPath).metadata();
		const exif = await extractExif(Buffer.from(buffer));

		const url = `/pics/${filename}`;

		images.push({
			id,
			hash,
			originalWidth: metadata.width ?? 0,
			originalHeight: metadata.height ?? 0,
			alt: '',
			exif,
			variants: [
				{
					width: metadata.width ?? 0,
					format: 'jpeg' as const,
					url,
					original: true,
					size: buffer.byteLength
				}
			]
		});
	}

	// Sort by date taken (newest first), fallback to filename
	images.sort((a, b) => {
		const da = a.exif.dateTaken ?? '';
		const db = b.exif.dateTaken ?? '';
		if (da && db) return db.localeCompare(da);
		if (da) return -1;
		if (db) return 1;
		return b.id.localeCompare(a.id);
	});

	const manifest = {
		version: 2,
		r2BaseUrl: '',
		images
	};

	// Write manifest.ts
	const json = JSON.stringify(manifest, null, 2);
	const ts = `// Generated by gen-manifest.ts — do not edit manually

interface ExifData {
\tcamera: string | null;
\taperture: number | null;
\tshutterSpeed: string | null;
\tiso: number | null;
\tfocalLength: number | null;
\tdateTaken: string | null;
}

interface ImageVariant {
\twidth: number;
\tformat: 'webp' | 'jpeg';
\turl: string;
\toriginal?: boolean;
\tsize?: number;
}

interface ManifestEntry {
\tid: string;
\thash: string;
\toriginalWidth: number;
\toriginalHeight: number;
\talt: string;
\texif: ExifData;
\tvariants: ImageVariant[];
}

interface Manifest {
\tversion: number;
\tr2BaseUrl: string;
\timages: ManifestEntry[];
}

const manifest: Manifest = ${json};

export default manifest;
`;

	const formatted = await prettier.format(ts, { filepath: MANIFEST_PATH, parser: 'typescript' });
	await writeFile(MANIFEST_PATH, formatted);

	console.log(`\nDone. ${images.length} images. Manifest written.`);
}

main().catch((err) => {
	console.error('Fatal:', err);
	process.exit(1);
});
